development:
  adapter: postgresql
  encoding: unicode
  database: lapsus_development
  pool: 5
  username: johngallagher
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: lapsus_test
  pool: 5
  username: johngallagher
  password:
  host: localhost
